<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0101ENCoursera23911160-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M1_R_Basics/images/IDSNlogo.png" width="200" align="center">
</a>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

There are 10 tasks in this final project. All tasks will be graded by your peers who are also completing this assignment within the same session.

You need to submit the following the screenshot for the code and output for each task for review.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [1]:
require("httr")
require("rvest")
install.packages('xml2')
library('xml2')
library(httr)
library(rvest)

Loading required package: httr
Loading required package: rvest
Loading required package: xml2
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this

URL [https://en.wikipedia.org/w/index.php?title=Template\:COVID-19\_testing_by_country](https://en.wikipedia.org/w/index.php?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0101ENCoursera23911160-2022-01-01&title=Template%3ACOVID-19\_testing_by_country) using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [1]:
get_wiki_covid19_page <- function() {
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ? 
  # Wiki page base
    wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
    wiki_lst<- list(title = "Template:COVID-19_testing_by_country")
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
    wiki_response <- GET(wiki_base_url, query = wiki_params) 
  # Use the `return` function to return the response
    return (wiki_response)}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [2]:
# Call the get_wiki_covid19_page function and print the response
wiki_data<-get_wiki_covid19_page
print(wiki_data)

function() {
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country
  # Which has two parts:
    # 1) base URL `https://en.wikipedia.org/w/index.php
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
  # Wiki page base
    wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
    wiki_lst<- list(title = "Template:COVID-19_testing_by_country")
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
    wiki_response <- GET(wiki_base_url, query = wiki_params)
  # Use the `return` function to return the response
    return (wiki_response)}

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0101ENCoursera23911160-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [4]:
# Get the root html node from the http response in task 1 
root_node <- read_html("https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country ")

Get the first table in the HTML root node using `html_node` function

In [5]:
# Get the table node from the root html node
table <- html_node(root_node, "table")

Read the table node as a data frame using `html_table` function

In [6]:
# Read the table node and convert it into a data frame, and print the data frame for review
df<-  html_table(table )
head(df)

  Country or region   Date[a]     Tested  Units[b] Confirmed(cases)
1 Afghanistan         17 Dec 2020 154,767 samples  49,621
2 Albania             18 Feb 2021 428,654 samples  96,838
3 Algeria             2 Nov 2020  230,553 samples  58,574
4 Andorra             23 Feb 2022 300,307 samples  37,958
5 Angola              2 Feb 2021  399,228 samples  20,981
6 Antigua and Barbuda 6 Mar 2021  15,268  samples  832
  Confirmed /tested,% Tested /population,% Confirmed /population,% Ref.
1 32.1                0.40                 0.13                    [1]
2 22.6                15.0                 3.4                     [2]
3 25.4                0.53                 0.13                    [3][4]
4 12.6                387                  49.0                    [5]
5 5.3                 1.3                  0.067                   [6]
6 5.4                 15.9                 0.86                    [7]

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [7]:
# Print the summary of the data frame
summary(df)

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`.

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [3]:
preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)
    # Remove the World row
    data_frame<-data_frame[!(data_frame$`Country or region`=="World"),]
    # Remove the last row
    data_frame <- data_frame[1:172, ]
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units[b]"] <- NULL
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
    data_frame$'confirmed.tested.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.tested.ratio`))
    data_frame$'tested.population.ratio' <- as.numeric(gsub(",","",data_frame$`tested.population.ratio`))
    data_frame$'confirmed.population.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.population.ratio`))
    return(data_frame)}

Call the `preprocess_covid_data_frame` function

In [9]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
new_df<- preprocess_covid_data_frame(df)
head(new_df)

  country             date        tested confirmed confirmed.tested.ratio
1 Afghanistan         17 Dec 2020 154767 49621     32.1
2 Albania             18 Feb 2021 428654 96838     22.6
3 Algeria             2 Nov 2020  230553 58574     25.4
4 Andorra             23 Feb 2022 300307 37958     12.6
5 Angola              2 Feb 2021  399228 20981      5.3
6 Antigua and Barbuda 6 Mar 2021   15268   832      5.4
  tested.population.ratio confirmed.population.ratio
1   0.40                   0.130
2  15.00                   3.400
3   0.53                   0.130
4 387.00                  49.000
5   1.30                   0.067
6  15.90                   0.860

Get the summary of the processed data frame again

In [10]:
# Print the summary of the processed data frame again
summary(new_df)

                country             date         tested
 Afghanistan        :  1   19 Sep 2022: 10   Min.   :     3880
 Albania            :  1   23 Sep 2022:  6   1st Qu.:   512037
 Algeria            :  1   1 Mar 2021 :  3   Median :  3029859
 Andorra            :  1   18 Sep 2022:  3   Mean   : 30927182
 Angola             :  1   20 Sep 2022:  3   3rd Qu.: 11845414
 Antigua and Barbuda:  1   22 Sep 2022:  3   Max.   :929349291
 (Other)            :166   (Other)    :144
   confirmed        confirmed.tested.ratio tested.population.ratio
 Min.   :       0   Min.   : 0.00          Min.   :   0.0065
 1st Qu.:   37042   1st Qu.: 5.00          1st Qu.:   9.4250
 Median :  267801   Median :10.05          Median :  46.9500
 Mean   : 2420746   Mean   :11.14          Mean   : 171.4066
 3rd Qu.: 1186031   3rd Qu.:15.32          3rd Qu.: 151.2500
 Max.   :90749469   Max.   :42.80          Max.   :3075.0000

 confirmed.population.ratio
 Min.   : 0.000
 1st Qu.: 0.425
 Median : 6.100
 Mean   :12.251
 3rd Qu.:15.675
 Max.   :67.800

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

*   **country** - The name of the country
*   **date** - Reported date
*   **tested** - Total tested cases by the reported date
*   **confirmed** - Total confirmed cases by the reported date
*   **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
*   **tested.population.ratio** - The ratio of tested cases to the population of the country
*   **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [11]:
# Export the data frame to a csv file
write.csv(new_df, "covid_dataset.csv")

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [12]:
# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/covid_dataset.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/resources/v2/M5_Final/covid_dataset.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [13]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [14]:
# Read covid_data_frame_csv from the csv file
data_frame <- read.csv("covid_dataset.csv", header=TRUE, sep=",")
# Get the 5th to 10th rows, with two "country" "confirmed" columns
sub_df<-data_frame[c(5:10),c("country", "confirmed")]
sub_df

   country             confirmed
5  Angola                 20981
6  Antigua and Barbuda      832
7  Argentina            9060495
8  Armenia               422963
9  Australia           10112229
10 Austria              5073706

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [15]:
# Get the total confirmed cases worldwide
total_confirmed_cases<-sum(sub_df$confirmed)
print(total_confirmed_cases)
# Get the total tested cases worldwide
total_tested_cases=sum(data_frame$tested)
print(total_tested_cases)
# Get the positive ratio (confirmed / tested)
positive_ratio=total_confirmed_cases/total_tested_cases
print(positive_ratio)

[1] 24691206
[1] 5319475275
[1] 0.004641662

## TASK 6: Get a country list which reported their testing data

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [16]:
# Get the `country` column
data_frame$country

  [1] Afghanistan            Albania                Algeria
  [4] Andorra                Angola                 Antigua and Barbuda
  [7] Argentina              Armenia                Australia
 [10] Austria                Azerbaijan             Bahamas
 [13] Bahrain                Bangladesh             Barbados
 [16] Belarus                Belgium                Belize
 [19] Benin                  Bhutan                 Bolivia
 [22] Bosnia and Herzegovina Botswana               Brazil
 [25] Brunei                 Bulgaria               Burkina Faso
 [28] Burundi                Cambodia               Cameroon
 [31] Canada                 Chad                   Chile
 [34] China[c]               Colombia               Costa Rica
 [37] Croatia                Cuba                   Cyprus[d]
 [40] Czechia                Denmark[e]             Djibouti
 [43] Dominica               Dominican Republic     DR Congo
 [46] Ecuador                Egypt                  El Salvador
 [49] Equatorial Guinea      Estonia                Eswatini
 [52] Ethiopia               Faroe Islands          Fiji
 [55] Finland                France[f][g]           Gabon
 [58] Gambia                 Georgia[h]             Germany
 [61] Ghana                  Greece                 Greenland
 [64] Grenada                Guatemala              Guinea
 [67] Guinea-Bissau          Guyana                 Haiti
 [70] Honduras               Hungary                Iceland
 [73] India                  Indonesia              Iran
 [76] Iraq                   Ireland                Israel
 [79] Italy                  Ivory Coast            Jamaica
 [82] Japan                  Jordan                 Kazakhstan
 [85] Kenya                  Kosovo                 Kuwait
 [88] Kyrgyzstan             Laos                   Latvia
 [91] Lebanon                Lesotho                Liberia
 [94] Libya                  Lithuania              Luxembourg[i]
 [97] Madagascar             Malawi                 Malaysia
[100] Maldives               Mali                   Malta
[103] Mauritania             Mauritius              Mexico
[106] Moldova[j]             Mongolia               Montenegro
[109] Morocco                Mozambique             Myanmar
[112] Namibia                Nepal                  Netherlands
[115] New Caledonia          New Zealand            Niger
[118] Nigeria                North Korea            North Macedonia
[121] Northern Cyprus[k]     Norway                 Oman
[124] Pakistan               Palestine              Panama
[127] Papua New Guinea       Paraguay               Peru
[130] Philippines            Poland                 Portugal
[133] Qatar                  Romania                Russia
[136] Rwanda                 Saint Kitts and Nevis  Saint Lucia
[139] Saint Vincent          San Marino             Saudi Arabia
[142] Senegal                Serbia                 Singapore
[145] Slovakia               Slovenia               South Africa
[148] South Korea            South Sudan            Spain
[151] Sri Lanka              Sudan                  Sweden
[154] Switzerland[l]         Taiwan[m]              Tanzania
[157] Thailand               Togo                   Trinidad and Tobago
[160] Tunisia                Turkey                 Uganda
[163] Ukraine                United Arab Emirates   United Kingdom
[166] United States          Uruguay                Uzbekistan
[169] Venezuela              Vietnam                Zambia
[172] Zimbabwe
172 Levels: Afghanistan Albania Algeria Andorra Angola ... Zimbabwe

In [17]:
# Check its class (should be Factor)
class(data_frame$country)

[1] "factor"

In [18]:
# Conver the country column into character so that you can easily sort them
data_frame$country<-as.character(data_frame$country)
class(data_frame$country)

[1] "character"

In [19]:
# Sort the countries AtoZ
data_frame[order(data_frame$country),]

lst_country<-list(data_frame$country)
print(lst_country)

    X   country                date        tested    confirmed
1    1  Afghanistan            17 Dec 2020    154767    49621
2    2  Albania                18 Feb 2021    428654    96838
3    3  Algeria                2 Nov 2020     230553    58574
4    4  Andorra                23 Feb 2022    300307    37958
5    5  Angola                 2 Feb 2021     399228    20981
6    6  Antigua and Barbuda    6 Mar 2021      15268      832
7    7  Argentina              16 Apr 2022  35716069  9060495
8    8  Armenia                29 May 2022   3099602   422963
9    9  Australia              9 Sep 2022   78548492 10112229
10  10  Austria                24 Sep 2022 197232756  5073706
11  11  Azerbaijan             11 May 2022   6838458   792638
12  12  Bahamas                14 Sep 2022    252462    37187
13  13  Bahrain                23 Sep 2022  10349784   677961
14  14  Bangladesh             24 Jul 2021   7417714  1151644
15  15  Barbados               22 Sep 2022    763590   102383
16  16  Belarus                9 May 2022   13217569   982809
17  17  Belgium                19 Sep 2022  35472608  4517212
18  18  Belize                 8 Jun 2022     572900    60694
19  19  Benin                  4 May 2021     595112     7884
20  20  Bhutan                 28 Feb 2022   1736168    12702
21  21  Bolivia                5 Jun 2022    4358669   910228
22  22  Bosnia and Herzegovina 6 Sep 2022    1847988   310023
23  23  Botswana               11 Jan 2022   2026898   232432
24  24  Brazil                 19 Feb 2021  23561497 10081676
25  25  Brunei                 2 Aug 2021     153804      338
26  26  Bulgaria               23 Sep 2022  10531568  1254682
27  27  Burkina Faso           4 Mar 2021     158777    12123
28  28  Burundi                5 Jan 2021      90019      884
29  29  Cambodia               1 Aug 2021    1812706    77914
30  30  Cameroon               18 Feb 2021    942685    32681
⋮   ⋮   ⋮                      ⋮           ⋮         ⋮
143 143 Serbia                 22 Sep 2022  10956266  2345665
144 144 Singapore              3 Aug 2021   16206203    65315
145 145 Slovakia               25 Sep 2022   7293263  1841580
146 146 Slovenia               25 Sep 2022   2740420  1171703
147 147 South Africa           24 May 2021  11378282  1637848
148 148 South Korea            1 Mar 2021    6592010    90029
149 149 South Sudan            26 May 2021    164472    10688
150 150 Spain                  1 Jul 2021   54128524  3821305
151 151 Sri Lanka              30 Mar 2021   2384745    93128
152 152 Sudan                  7 Jan 2021     158804    23316
153 153 Sweden                 24 May 2021   9996795  1074751
154 154 Switzerland[l]         19 Sep 2022  22748937  4087079
155 155 Taiwan[m]              20 Sep 2022  25449381  6043509
156 156 Tanzania               18 Nov 2020      3880      509
157 157 Thailand               4 Mar 2021    1579597    26162
158 158 Togo                   19 Sep 2022    790187    38804
159 159 Trinidad and Tobago    3 Jan 2022     512730    92997
160 160 Tunisia                23 Aug 2021   2893625   703732
161 161 Turkey                 2 Jul 2021   61236294  5435831
162 162 Uganda                 11 Feb 2021    852444    39979
163 163 Ukraine                24 Nov 2021  15648456  3367461
164 164 United Arab Emirates   23 Sep 2022 189271991  1024845
165 165 United Kingdom         19 May 2022 522526476 22232377
166 166 United States          29 Jul 2022 929349291 90749469
167 167 Uruguay                16 Apr 2022   6089116   895592
168 168 Uzbekistan             7 Sep 2020    2630000    43975
169 169 Venezuela              30 Mar 2021   3179074   159149
170 170 Vietnam                28 Aug 2022  45772571 11403302
171 171 Zambia                 10 Mar 2022   3301860   314850
172 172 Zimbabwe               19 Sep 2022   2503212   257156
    confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
1   32.10                     0.40                  0.1300
2   22.60                    15.00                  3.4000
3   25.40                     0.53                  0.1300
4   12.60                   387.00                 49.0000
5    5.30                     1.30                  0.0670
6    5.40                    15.90                  0.8600
7   25.40                    78.30                 20.0000
8   13.60                   105.00                 14.3000
9   12.90                   313.00                 40.3000
10   2.60                  2215.00                 56.7000
11  11.60                    69.10                  8.0000
12  14.70                    65.50                  9.6000
13   6.60                   659.00                 43.2000
14  15.50                     4.50                  0.7000
15  13.40                   266.00                 35.7000
16   7.40                   139.00                 10.4000
17  12.70                   308.00                 39.2000
18  10.60                   140.00                 14.9000
19   1.30                     5.10                  0.0670
20   0.73                   234.00                  1.7100
21  20.90                    38.10                  8.0000
22  16.80                    54.00                  9.1000
23  11.50                    89.90                 10.3000
24  42.80                    11.20                  4.8000
25   0.22                    33.50                  0.0740
26  11.90                   152.00                 18.1000
27   7.60                     0.76                  0.0580
28   0.98                     0.76                  0.0074
29   4.30                    11.20                  0.4800
30   3.50                     3.60                  0.1200
⋮   ⋮                      ⋮                       ⋮
143 21.40                   157.0000               33.70000
144  0.40                   284.0000                1.10000
145 25.30                   134.0000               33.70000
146 42.80                   131.0000               56.00000
147 14.40                    19.2000                2.80000
148  1.40                    12.7000                0.17000
149  6.50                     1.3000                0.08400
150  7.10                   116.0000                8.20000
151  3.90                    10.9000                0.43000
152 14.70                     0.3600                0.05300
153 10.80                    96.8000               10.40000
154 18.00                   264.0000               47.50000
155 23.75                   107.8000               25.60300
156 13.10                     0.0065                0.00085
157  1.70                     2.3000                0.03800
158  4.90                     9.2000                0.45000
159 18.10                    37.6000                6.80000
160 24.30                    24.5000                6.00000
161  8.90                    73.6000                6.50000
162  4.70                     1.9000                0.08700
163 21.50                    37.2000                8.00000
164  0.54                  1972.0000               10.70000
165  4.30                   774.0000               32.90000
166  9.80                   281.0000               27.40000
167 14.70                   175.0000               25.80000
168  1.70                     7.7000                0.13000
169  5.00                    11.0000                0.55000
170 24.90                    46.4000               11.60000
171  9.50                    19.0000                1.80000
172 10.30                    16.8000                1.70000

[[1]]
  [1] "Afghanistan"            "Albania"                "Algeria"
  [4] "Andorra"                "Angola"                 "Antigua and Barbuda"
  [7] "Argentina"              "Armenia"                "Australia"
 [10] "Austria"                "Azerbaijan"             "Bahamas"
 [13] "Bahrain"                "Bangladesh"             "Barbados"
 [16] "Belarus"                "Belgium"                "Belize"
 [19] "Benin"                  "Bhutan"                 "Bolivia"
 [22] "Bosnia and Herzegovina" "Botswana"               "Brazil"
 [25] "Brunei"                 "Bulgaria"               "Burkina Faso"
 [28] "Burundi"                "Cambodia"               "Cameroon"
 [31] "Canada"                 "Chad"                   "Chile"
 [34] "China[c]"               "Colombia"               "Costa Rica"
 [37] "Croatia"                "Cuba"                   "Cyprus[d]"
 [40] "Czechia"                "Denmark[e]"             "Djibouti"
 [43] "Dominica"               "Dominican Republic"     "DR Congo"
 [46] "Ecuador"                "Egypt"                  "El Salvador"
 [49] "Equatorial Guinea"      "Estonia"                "Eswatini"
 [52] "Ethiopia"               "Faroe Islands"          "Fiji"
 [55] "Finland"                "France[f][g]"           "Gabon"
 [58] "Gambia"                 "Georgia[h]"             "Germany"
 [61] "Ghana"                  "Greece"                 "Greenland"
 [64] "Grenada"                "Guatemala"              "Guinea"
 [67] "Guinea-Bissau"          "Guyana"                 "Haiti"
 [70] "Honduras"               "Hungary"                "Iceland"
 [73] "India"                  "Indonesia"              "Iran"
 [76] "Iraq"                   "Ireland"                "Israel"
 [79] "Italy"                  "Ivory Coast"            "Jamaica"
 [82] "Japan"                  "Jordan"                 "Kazakhstan"
 [85] "Kenya"                  "Kosovo"                 "Kuwait"
 [88] "Kyrgyzstan"             "Laos"                   "Latvia"
 [91] "Lebanon"                "Lesotho"                "Liberia"
 [94] "Libya"                  "Lithuania"              "Luxembourg[i]"
 [97] "Madagascar"             "Malawi"                 "Malaysia"
[100] "Maldives"               "Mali"                   "Malta"
[103] "Mauritania"             "Mauritius"              "Mexico"
[106] "Moldova[j]"             "Mongolia"               "Montenegro"
[109] "Morocco"                "Mozambique"             "Myanmar"
[112] "Namibia"                "Nepal"                  "Netherlands"
[115] "New Caledonia"          "New Zealand"            "Niger"
[118] "Nigeria"                "North Korea"            "North Macedonia"
[121] "Northern Cyprus[k]"     "Norway"                 "Oman"
[124] "Pakistan"               "Palestine"              "Panama"
[127] "Papua New Guinea"       "Paraguay"               "Peru"
[130] "Philippines"            "Poland"                 "Portugal"
[133] "Qatar"                  "Romania"                "Russia"
[136] "Rwanda"                 "Saint Kitts and Nevis"  "Saint Lucia"
[139] "Saint Vincent"          "San Marino"             "Saudi Arabia"
[142] "Senegal"                "Serbia"                 "Singapore"
[145] "Slovakia"               "Slovenia"               "South Africa"
[148] "South Korea"            "South Sudan"            "Spain"
[151] "Sri Lanka"              "Sudan"                  "Sweden"
[154] "Switzerland[l]"         "Taiwan[m]"              "Tanzania"
[157] "Thailand"               "Togo"                   "Trinidad and Tobago"
[160] "Tunisia"                "Turkey"                 "Uganda"
[163] "Ukraine"                "United Arab Emirates"   "United Kingdom"
[166] "United States"          "Uruguay"                "Uzbekistan"
[169] "Venezuela"              "Vietnam"                "Zambia"
[172] "Zimbabwe"

In [20]:
# Sort the countries ZtoA
data_frame[order(data_frame$country,decreasing=TRUE),]
# Print the sorted ZtoA list
sorted_country_lst<-list(data_frame[order(data_frame$country,decreasing=TRUE),])
print(sorted_country_lst)

    X   country                date        tested    confirmed
172 172 Zimbabwe               19 Sep 2022   2503212   257156
171 171 Zambia                 10 Mar 2022   3301860   314850
170 170 Vietnam                28 Aug 2022  45772571 11403302
169 169 Venezuela              30 Mar 2021   3179074   159149
168 168 Uzbekistan             7 Sep 2020    2630000    43975
167 167 Uruguay                16 Apr 2022   6089116   895592
166 166 United States          29 Jul 2022 929349291 90749469
165 165 United Kingdom         19 May 2022 522526476 22232377
164 164 United Arab Emirates   23 Sep 2022 189271991  1024845
163 163 Ukraine                24 Nov 2021  15648456  3367461
162 162 Uganda                 11 Feb 2021    852444    39979
161 161 Turkey                 2 Jul 2021   61236294  5435831
160 160 Tunisia                23 Aug 2021   2893625   703732
159 159 Trinidad and Tobago    3 Jan 2022     512730    92997
158 158 Togo                   19 Sep 2022    790187    38804
157 157 Thailand               4 Mar 2021    1579597    26162
156 156 Tanzania               18 Nov 2020      3880      509
155 155 Taiwan[m]              20 Sep 2022  25449381  6043509
154 154 Switzerland[l]         19 Sep 2022  22748937  4087079
153 153 Sweden                 24 May 2021   9996795  1074751
152 152 Sudan                  7 Jan 2021     158804    23316
151 151 Sri Lanka              30 Mar 2021   2384745    93128
150 150 Spain                  1 Jul 2021   54128524  3821305
149 149 South Sudan            26 May 2021    164472    10688
148 148 South Korea            1 Mar 2021    6592010    90029
147 147 South Africa           24 May 2021  11378282  1637848
146 146 Slovenia               25 Sep 2022   2740420  1171703
145 145 Slovakia               25 Sep 2022   7293263  1841580
144 144 Singapore              3 Aug 2021   16206203    65315
143 143 Serbia                 22 Sep 2022  10956266  2345665
⋮   ⋮   ⋮                      ⋮           ⋮         ⋮
30  30  Cameroon               18 Feb 2021    942685    32681
29  29  Cambodia               1 Aug 2021    1812706    77914
28  28  Burundi                5 Jan 2021      90019      884
27  27  Burkina Faso           4 Mar 2021     158777    12123
26  26  Bulgaria               23 Sep 2022  10531568  1254682
25  25  Brunei                 2 Aug 2021     153804      338
24  24  Brazil                 19 Feb 2021  23561497 10081676
23  23  Botswana               11 Jan 2022   2026898   232432
22  22  Bosnia and Herzegovina 6 Sep 2022    1847988   310023
21  21  Bolivia                5 Jun 2022    4358669   910228
20  20  Bhutan                 28 Feb 2022   1736168    12702
19  19  Benin                  4 May 2021     595112     7884
18  18  Belize                 8 Jun 2022     572900    60694
17  17  Belgium                19 Sep 2022  35472608  4517212
16  16  Belarus                9 May 2022   13217569   982809
15  15  Barbados               22 Sep 2022    763590   102383
14  14  Bangladesh             24 Jul 2021   7417714  1151644
13  13  Bahrain                23 Sep 2022  10349784   677961
12  12  Bahamas                14 Sep 2022    252462    37187
11  11  Azerbaijan             11 May 2022   6838458   792638
10  10  Austria                24 Sep 2022 197232756  5073706
9    9  Australia              9 Sep 2022   78548492 10112229
8    8  Armenia                29 May 2022   3099602   422963
7    7  Argentina              16 Apr 2022  35716069  9060495
6    6  Antigua and Barbuda    6 Mar 2021      15268      832
5    5  Angola                 2 Feb 2021     399228    20981
4    4  Andorra                23 Feb 2022    300307    37958
3    3  Algeria                2 Nov 2020     230553    58574
2    2  Albania                18 Feb 2021    428654    96838
1    1  Afghanistan            17 Dec 2020    154767    49621
    confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
172 10.30                    16.8000                1.70000
171  9.50                    19.0000                1.80000
170 24.90                    46.4000               11.60000
169  5.00                    11.0000                0.55000
168  1.70                     7.7000                0.13000
167 14.70                   175.0000               25.80000
166  9.80                   281.0000               27.40000
165  4.30                   774.0000               32.90000
164  0.54                  1972.0000               10.70000
163 21.50                    37.2000                8.00000
162  4.70                     1.9000                0.08700
161  8.90                    73.6000                6.50000
160 24.30                    24.5000                6.00000
159 18.10                    37.6000                6.80000
158  4.90                     9.2000                0.45000
157  1.70                     2.3000                0.03800
156 13.10                     0.0065                0.00085
155 23.75                   107.8000               25.60300
154 18.00                   264.0000               47.50000
153 10.80                    96.8000               10.40000
152 14.70                     0.3600                0.05300
151  3.90                    10.9000                0.43000
150  7.10                   116.0000                8.20000
149  6.50                     1.3000                0.08400
148  1.40                    12.7000                0.17000
147 14.40                    19.2000                2.80000
146 42.80                   131.0000               56.00000
145 25.30                   134.0000               33.70000
144  0.40                   284.0000                1.10000
143 21.40                   157.0000               33.70000
⋮   ⋮                      ⋮                       ⋮
30   3.50                     3.60                  0.1200
29   4.30                    11.20                  0.4800
28   0.98                     0.76                  0.0074
27   7.60                     0.76                  0.0580
26  11.90                   152.00                 18.1000
25   0.22                    33.50                  0.0740
24  42.80                    11.20                  4.8000
23  11.50                    89.90                 10.3000
22  16.80                    54.00                  9.1000
21  20.90                    38.10                  8.0000
20   0.73                   234.00                  1.7100
19   1.30                     5.10                  0.0670
18  10.60                   140.00                 14.9000
17  12.70                   308.00                 39.2000
16   7.40                   139.00                 10.4000
15  13.40                   266.00                 35.7000
14  15.50                     4.50                  0.7000
13   6.60                   659.00                 43.2000
12  14.70                    65.50                  9.6000
11  11.60                    69.10                  8.0000
10   2.60                  2215.00                 56.7000
9   12.90                   313.00                 40.3000
8   13.60                   105.00                 14.3000
7   25.40                    78.30                 20.0000
6    5.40                    15.90                  0.8600
5    5.30                     1.30                  0.0670
4   12.60                   387.00                 49.0000
3   25.40                     0.53                  0.1300
2   22.60                    15.00                  3.4000
1   32.10                     0.40                  0.1300

[[1]]
      X                country        date    tested    confirmed
172 172               Zimbabwe 19 Sep 2022   2503212   257156.000
171 171                 Zambia 10 Mar 2022   3301860   314850.000
170 170                Vietnam 28 Aug 2022  45772571 11403302.000
169 169              Venezuela 30 Mar 2021   3179074   159149.000
168 168             Uzbekistan  7 Sep 2020   2630000    43975.000
167 167                Uruguay 16 Apr 2022   6089116   895592.000
166 166          United States 29 Jul 2022 929349291 90749469.000
165 165         United Kingdom 19 May 2022 522526476 22232377.000
164 164   United Arab Emirates 23 Sep 2022 189271991  1024845.000
163 163                Ukraine 24 Nov 2021  15648456  3367461.000
162 162                 Uganda 11 Feb 2021    852444    39979.000
161 161                 Turkey  2 Jul 2021  61236294  5435831.000
160 160                Tunisia 23 Aug 2021   2893625   703732.000
159 159    Trinidad and Tobago  3 Jan 2022    512730    92997.000
158 158                   Togo 19 Sep 2022    790187    38804.000
157 157               Thailand  4 Mar 2021   1579597    26162.000
156 156               Tanzania 18 Nov 2020      3880      509.000
155 155              Taiwan[m] 20 Sep 2022  25449381  6043509.000
154 154         Switzerland[l] 19 Sep 2022  22748937  4087079.000
153 153                 Sweden 24 May 2021   9996795  1074751.000
152 152                  Sudan  7 Jan 2021    158804    23316.000
151 151              Sri Lanka 30 Mar 2021   2384745    93128.000
150 150                  Spain  1 Jul 2021  54128524  3821305.000
149 149            South Sudan 26 May 2021    164472    10688.000
148 148            South Korea  1 Mar 2021   6592010    90029.000
147 147           South Africa 24 May 2021  11378282  1637848.000
146 146               Slovenia 25 Sep 2022   2740420  1171703.000
145 145               Slovakia 25 Sep 2022   7293263  1841580.000
144 144              Singapore  3 Aug 2021  16206203    65315.000
143 143                 Serbia 22 Sep 2022  10956266  2345665.000
142 142                Senegal 12 Jul 2021    624502    46509.000
141 141           Saudi Arabia 26 Apr 2022  41849069   753632.000
140 140             San Marino 25 Sep 2022    174326    20671.000
139 139          Saint Vincent 11 Sep 2022    111942     9446.000
138 138            Saint Lucia 10 Sep 2022    208817    28894.000
137 137  Saint Kitts and Nevis 26 Aug 2021     30231      995.000
136 136                 Rwanda  6 Oct 2021   2885812    98209.000
135 135                 Russia  6 Jun 2022 295542733 18358459.000
134 134                Romania 29 Jan 2021   5405393   724250.000
133 133                  Qatar 23 Sep 2022   3937326   446277.000
132 132               Portugal  5 Jan 2022  27515490  1499976.000
131 131                 Poland 27 Apr 2022  36064311  5993861.000
130 130            Philippines 20 Sep 2022  32630852  3925326.000
129 129                   Peru 21 Aug 2022  34036166  4075910.000
128 128               Paraguay 27 Mar 2022   2609819   647950.000
127 127       Papua New Guinea 17 Feb 2021     47490      961.000
126 126                 Panama 17 Sep 2022   7037466   985814.000
125 125              Palestine  5 Feb 2022   3078533   574105.000
124 124               Pakistan  5 Mar 2021   9173593   588728.000
123 123                   Oman 28 Oct 2020    509959   114434.000
122 122                 Norway 20 Jan 2022   9811888   554778.000
121 121     Northern Cyprus[k] 12 Jul 2022   7096998   103034.000
120 120        North Macedonia  1 Jul 2021    881870   155689.000
119 119            North Korea 25 Nov 2020     16914        0.000
118 118                Nigeria 28 Feb 2021   1544008   155657.000
117 117                  Niger 22 Feb 2021     79321     4740.000
116 116            New Zealand 18 Sep 2022   7529992  1752613.000
115 115          New Caledonia  3 Sep 2021     41962      136.000
114 114            Netherlands  6 Jul 2021  14526293  1692834.000
113 113                  Nepal 26 Jul 2022   5804358   984475.000
112 112                Namibia  4 Jul 2022   1062663   166229.000
111 111                Myanmar 16 Sep 2021   4047680   440741.000
110 110             Mozambique 22 Jul 2021    688570   105866.000
109 109                Morocco 19 Sep 2022  13813597  1264807.000
108 108             Montenegro 10 May 2021    394388    98449.000
107 107               Mongolia 10 Jul 2021   3354200   136053.000
106 106             Moldova[j] 20 Apr 2022   3213594   516864.000
105 105                 Mexico 15 Oct 2021  10503678  3749860.000
104 104              Mauritius 22 Nov 2020    289552      494.000
103 103             Mauritania 16 Apr 2021    268093    18103.000
102 102                  Malta  8 Sep 2021   1211456    36606.000
101 101                   Mali  7 Jul 2021    322504    14449.000
100 100               Maldives 13 Mar 2022   2216560   174658.000
99   99               Malaysia  7 Sep 2021  23705425  1880734.000
98   98                 Malawi 19 Sep 2022    614698    87981.000
97   97             Madagascar 19 Feb 2021    119608    19831.000
96   96          Luxembourg[i] 12 May 2022   4248188   244182.000
95   95              Lithuania 20 Sep 2022   8863984  1127285.000
94   94                  Libya 14 Apr 2022   2578215   501862.000
93   93                Liberia 17 Jul 2021    128246     5396.000
92   92                Lesotho 30 Mar 2022    431221    32910.000
91   91                Lebanon 14 Jun 2021   4599186   542649.000
90   90                 Latvia  5 Sep 2021   3630095   144518.000
89   89                   Laos  1 Mar 2021    114030       45.000
88   88             Kyrgyzstan 10 Feb 2021    695415    85253.000
87   87                 Kuwait  9 Mar 2022   7754247   624573.000
86   86                 Kosovo 31 May 2021    611357   107410.000
85   85                  Kenya  5 Mar 2021   1322806   107729.000
84   84             Kazakhstan 28 May 2021  11575012   385144.000
83   83                 Jordan  6 Jun 2021   7407053   739847.000
82   82                  Japan  1 Mar 2021   8487288   432773.000
81   81                Jamaica 19 Sep 2022   1179414   151375.000
80   80            Ivory Coast  3 Mar 2021    429177    33285.000
79   79                  Italy 27 Sep 2022 246239458 22358487.000
78   78                 Israel 17 Jan 2022  41373364  1792137.000
77   77                Ireland  7 Sep 2022  12656618  1659034.000
76   76                   Iraq  3 Aug 2022  19090652  2448484.000
75   75                   Iran 31 May 2022  52269202  7232268.000
74   74              Indonesia 27 Sep 2022  70702673  6425849.000
73   73                  India  8 Jul 2022 866177937 43585554.000
72   72                Iceland  9 Aug 2022   1988652   203162.000
71   71                Hungary 10 May 2022  11394556  1909948.000
70   70               Honduras 26 Nov 2021   1133782   377859.000
69   69                  Haiti  8 Sep 2022    220983    33702.000
68   68                 Guyana 15 Jun 2022    648569    66129.000
67   67          Guinea-Bissau  7 Jul 2022    145231     8400.000
66   66                 Guinea 21 Jul 2021    494898    24878.000
65   65              Guatemala 19 Sep 2022   5798013  1116046.000
64   64                Grenada 11 May 2021     28684      161.000
63   63              Greenland 30 Jan 2022    164573    10662.000
62   62                 Greece 18 Sep 2022  93478498  4875215.000
61   61                  Ghana  3 Jul 2021   1305749    96708.000
60   60                Germany  7 Jul 2021  65247345  3733519.000
59   59             Georgia[h]  3 Nov 2021   4888787   732965.000
58   58                 Gambia 15 Feb 2021     43217     4469.000
57   57                  Gabon 23 Jul 2021    958807    25325.000
56   56           France[f][g] 15 May 2022 272417258 29183646.000
55   55                Finland 14 Jan 2022   9042453   371135.000
54   54                   Fiji 15 Sep 2022    661442    68223.000
53   53          Faroe Islands 27 Feb 2022    774000    34237.000
52   52               Ethiopia 24 Jun 2021   2981185   278446.000
51   51               Eswatini  8 Dec 2021    415110    49253.000
50   50                Estonia 19 Sep 2022   3509346   600911.000
49   49      Equatorial Guinea 19 Sep 2022    383104    16909.000
48   48            El Salvador 18 Mar 2022   1847861   161052.000
47   47                  Egypt 23 Jul 2021   3137519   283947.000
46   46                Ecuador 23 Jul 2021   1627189   480720.000
45   45               DR Congo 28 Feb 2021    124838    25961.000
44   44     Dominican Republic 22 Jul 2022   3574665   626030.000
43   43               Dominica 20 Jun 2022    209803    14821.000
42   42               Djibouti 28 Apr 2022    305941    15631.000
41   41             Denmark[e] 27 Sep 2022  66916254  3295332.000
40   40                Czechia 23 Sep 2022  22273525  4089884.000
39   39              Cyprus[d] 18 Sep 2022  26545841   585313.000
38   38                   Cuba 24 Sep 2022  14143613  1111146.000
37   37                Croatia 24 Sep 2022   5212841  1229014.000
36   36             Costa Rica  2 Nov 2021   2575363   561054.000
35   35               Colombia 22 Sep 2022  36519532  6306552.000
34   34               China[c] 31 Jul 2020 160000000    87655.000
33   33                  Chile 23 Sep 2022  44944221  4603514.000
32   32                   Chad  2 Mar 2021     99027     4020.000
31   31                 Canada 17 Sep 2022  64928884     4233.468
30   30               Cameroon 18 Feb 2021    942685    32681.000
29   29               Cambodia  1 Aug 2021   1812706    77914.000
28   28                Burundi  5 Jan 2021     90019      884.000
27   27           Burkina Faso  4 Mar 2021    158777    12123.000
26   26               Bulgaria 23 Sep 2022  10531568  1254682.000
25   25                 Brunei  2 Aug 2021    153804      338.000
24   24                 Brazil 19 Feb 2021  23561497 10081676.000
23   23               Botswana 11 Jan 2022   2026898   232432.000
22   22 Bosnia and Herzegovina  6 Sep 2022   1847988   310023.000
21   21                Bolivia  5 Jun 2022   4358669   910228.000
20   20                 Bhutan 28 Feb 2022   1736168    12702.000
19   19                  Benin  4 May 2021    595112     7884.000
18   18                 Belize  8 Jun 2022    572900    60694.000
17   17                Belgium 19 Sep 2022  35472608  4517212.000
16   16                Belarus  9 May 2022  13217569   982809.000
15   15               Barbados 22 Sep 2022    763590   102383.000
14   14             Bangladesh 24 Jul 2021   7417714  1151644.000
13   13                Bahrain 23 Sep 2022  10349784   677961.000
12   12                Bahamas 14 Sep 2022    252462    37187.000
11   11             Azerbaijan 11 May 2022   6838458   792638.000
10   10                Austria 24 Sep 2022 197232756  5073706.000
9     9              Australia  9 Sep 2022  78548492 10112229.000
8     8                Armenia 29 May 2022   3099602   422963.000
7     7              Argentina 16 Apr 2022  35716069  9060495.000
6     6    Antigua and Barbuda  6 Mar 2021     15268      832.000
5     5                 Angola  2 Feb 2021    399228    20981.000
4     4                Andorra 23 Feb 2022    300307    37958.000
3     3                Algeria  2 Nov 2020    230553    58574.000
2     2                Albania 18 Feb 2021    428654    96838.000
1     1            Afghanistan 17 Dec 2020    154767    49621.000
    confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
172                 10.300                 16.8000                    1.70000
171                  9.500                 19.0000                    1.80000
170                 24.900                 46.4000                   11.60000
169                  5.000                 11.0000                    0.55000
168                  1.700                  7.7000                    0.13000
167                 14.700                175.0000                   25.80000
166                  9.800                281.0000                   27.40000
165                  4.300                774.0000                   32.90000
164                  0.540               1972.0000                   10.70000
163                 21.500                 37.2000                    8.00000
162                  4.700                  1.9000                    0.08700
161                  8.900                 73.6000                    6.50000
160                 24.300                 24.5000                    6.00000
159                 18.100                 37.6000                    6.80000
158                  4.900                  9.2000                    0.45000
157                  1.700                  2.3000                    0.03800
156                 13.100                  0.0065                    0.00085
155                 23.750                107.8000                   25.60300
154                 18.000                264.0000                   47.50000
153                 10.800                 96.8000                   10.40000
152                 14.700                  0.3600                    0.05300
151                  3.900                 10.9000                    0.43000
150                  7.100                116.0000                    8.20000
149                  6.500                  1.3000                    0.08400
148                  1.400                 12.7000                    0.17000
147                 14.400                 19.2000                    2.80000
146                 42.800                131.0000                   56.00000
145                 25.300                134.0000                   33.70000
144                  0.400                284.0000                    1.10000
143                 21.400                157.0000                   33.70000
142                  7.400                  3.9000                    0.29000
141                  1.800                120.0000                    2.20000
140                 11.900                509.0000                   60.40000
139                  8.400                101.6000                    8.60000
138                 13.800                114.8000                   15.90000
137                  3.300                 57.6000                    1.90000
136                  3.400                 22.3000                    0.76000
135                  6.200                201.0000                   12.50000
134                 13.400                 27.9000                    3.70000
133                 11.300                137.0000                   15.50000
132                  5.500                268.0000                   14.60000
131                 16.600                 94.0000                   15.60000
130                 12.000                 32.3000                    3.90000
129                 12.000                103.7000                   12.40000
128                 24.800                 36.6000                    9.10000
127                  2.000                  0.5300                    0.01100
126                 14.000                168.0000                   23.60000
125                 18.600                 60.9000                   11.40000
124                  6.400                  4.2000                    0.27000
123                 22.400                 11.0000                    2.50000
122                  5.700                183.0000                   10.30000
121                  1.500               2177.0000                   31.60000
120                 17.700                 42.5000                    7.50000
119                  0.000                  0.0660                    0.00000
118                 10.100                  0.7500                    0.07600
117                  6.000                  0.3500                    0.02100
116                 23.300                151.0000                   35.20000
115                  0.320                 15.7000                    0.05000
114                 11.700                 83.4000                    9.70000
113                 17.000                 20.7000                    3.50000
112                 15.600                 38.7000                    6.10000
111                 10.900                  7.4000                    0.81000
110                 15.400                  2.2000                    0.34000
109                  9.200                 37.4000                    3.40000
108                 25.000                 62.5000                   15.60000
107                  4.100                100.0000                    4.10000
106                 16.100                122.0000                   19.60000
105                 35.700                  8.2000                    2.90000
104                  0.170                 22.9000                    0.03900
103                  6.800                  6.1000                    0.41000
102                  3.000                245.0000                    7.40000
101                  4.500                  1.6000                    0.07100
100                  7.900                398.0000                   31.30000
99                   7.900                 72.3000                    5.70000
98                  14.300                  3.2000                    0.46000
97                  16.600                  0.4600                    0.07600
96                   5.700                679.0000                   39.00000
95                  12.700                317.0000                   40.30000
94                  19.500                 37.6000                    7.30000
93                   4.200                  2.5000                    0.11000
92                   7.600                 21.5000                    1.60000
91                  11.800                 67.4000                    8.00000
90                   4.000                189.0000                    7.50000
89                   0.039                  1.6000                    0.00063
88                  12.300                 10.7000                    1.30000
87                   8.100                181.0000                   14.60000
86                  17.600                 33.8000                    5.90000
85                   8.100                  2.8000                    0.23000
84                   3.300                 62.1000                    2.10000
83                  10.000                 69.5000                    6.90000
82                   5.100                  6.7000                    0.34000
81                  12.800                 43.3000                    5.60000
80                   7.800                  1.6000                    0.13000
79                   9.100                408.0000                   37.00000
78                   4.300                451.0000                   19.50000
77                  13.100                257.0000                   33.70000
76                  12.800                 47.5000                    6.10000
75                  13.800                 62.8000                    8.70000
74                   9.100                 26.2000                    2.40000
73                   5.000                 63.0000                   31.70000
72                  10.200                546.0000                   55.80000
71                  16.800                118.0000                   19.80000
70                  33.300                 11.8000                    3.90000
69                  15.300                  1.9000                    0.29000
68                  10.200                 82.5000                    8.40000
67                   5.800                  7.7000                    0.45000
66                   5.000                  3.8000                    0.19000
65                  19.100                 33.6000                    6.40000

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [21]:
# Use a regular expression `United.+` to find matches
match_country <- grep("United.+",data_frame$country)
# Print the matched country names
print(data_frame$country[match_country])

[1] "United Arab Emirates" "United Kingdom"       "United States"

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [22]:

# Select a subset (should be only one row) of data frame based on a selected country name and columns
df_angola <- data_frame[data_frame$country == "Angola",c('country', 'confirmed',  'confirmed.population.ratio')]
print(df_angola)
# Select a subset (should be only one row) of data frame based on a selected country name and columns
df_argentina <- data_frame[data_frame$country == "Argentina",c('country', 'confirmed',  'confirmed.population.ratio')] 
print(df_argentina)

  country confirmed confirmed.population.ratio
5  Angola     20981                      0.067
    country confirmed confirmed.population.ratio
7 Argentina   9060495                         20

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [23]:
# Use if-else statement
# if (check which confirmed.population value is greater) {
#    print()
# } else {
#    print()
# }
if (df_argentina$confirmed.population > df_angola$confirmed.population) {
    print("In Argentina the risk of COVID-19 infection is higher. ")
  } else {
    print("In Angola the risk of COVID-19 infection is higher.")
 }

[1] "In Argentina the risk of COVID-19 infection is higher. "

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [24]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
subset(data_frame, subset = confirmed.population.ratio < 1)

    X   country             date        tested    confirmed
1     1 Afghanistan         17 Dec 2020    154767   49621
3     3 Algeria             2 Nov 2020     230553   58574
5     5 Angola              2 Feb 2021     399228   20981
6     6 Antigua and Barbuda 6 Mar 2021      15268     832
14   14 Bangladesh          24 Jul 2021   7417714 1151644
19   19 Benin               4 May 2021     595112    7884
25   25 Brunei              2 Aug 2021     153804     338
27   27 Burkina Faso        4 Mar 2021     158777   12123
28   28 Burundi             5 Jan 2021      90019     884
29   29 Cambodia            1 Aug 2021    1812706   77914
30   30 Cameroon            18 Feb 2021    942685   32681
32   32 Chad                2 Mar 2021      99027    4020
34   34 China[c]            31 Jul 2020 160000000   87655
45   45 DR Congo            28 Feb 2021    124838   25961
47   47 Egypt               23 Jul 2021   3137519  283947
52   52 Ethiopia            24 Jun 2021   2981185  278446
57   57 Gabon               23 Jul 2021    958807   25325
58   58 Gambia              15 Feb 2021     43217    4469
61   61 Ghana               3 Jul 2021    1305749   96708
64   64 Grenada             11 May 2021     28684     161
66   66 Guinea              21 Jul 2021    494898   24878
67   67 Guinea-Bissau       7 Jul 2022     145231    8400
69   69 Haiti               8 Sep 2022     220983   33702
80   80 Ivory Coast         3 Mar 2021     429177   33285
82   82 Japan               1 Mar 2021    8487288  432773
85   85 Kenya               5 Mar 2021    1322806  107729
89   89 Laos                1 Mar 2021     114030      45
93   93 Liberia             17 Jul 2021    128246    5396
97   97 Madagascar          19 Feb 2021    119608   19831
98   98 Malawi              19 Sep 2022    614698   87981
101 101 Mali                7 Jul 2021     322504   14449
103 103 Mauritania          16 Apr 2021    268093   18103
104 104 Mauritius           22 Nov 2020    289552     494
110 110 Mozambique          22 Jul 2021    688570  105866
111 111 Myanmar             16 Sep 2021   4047680  440741
115 115 New Caledonia       3 Sep 2021      41962     136
117 117 Niger               22 Feb 2021     79321    4740
118 118 Nigeria             28 Feb 2021   1544008  155657
119 119 North Korea         25 Nov 2020     16914       0
124 124 Pakistan            5 Mar 2021    9173593  588728
127 127 Papua New Guinea    17 Feb 2021     47490     961
136 136 Rwanda              6 Oct 2021    2885812   98209
142 142 Senegal             12 Jul 2021    624502   46509
148 148 South Korea         1 Mar 2021    6592010   90029
149 149 South Sudan         26 May 2021    164472   10688
151 151 Sri Lanka           30 Mar 2021   2384745   93128
152 152 Sudan               7 Jan 2021     158804   23316
156 156 Tanzania            18 Nov 2020      3880     509
157 157 Thailand            4 Mar 2021    1579597   26162
158 158 Togo                19 Sep 2022    790187   38804
162 162 Uganda              11 Feb 2021    852444   39979
168 168 Uzbekistan          7 Sep 2020    2630000   43975
169 169 Venezuela           30 Mar 2021   3179074  159149
    confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
1   32.100                  0.4000                 0.13000
3   25.400                  0.5300                 0.13000
5    5.300                  1.3000                 0.06700
6    5.400                 15.9000                 0.86000
14  15.500                  4.5000                 0.70000
19   1.300                  5.1000                 0.06700
25   0.220                 33.5000                 0.07400
27   7.600                  0.7600                 0.05800
28   0.980                  0.7600                 0.00740
29   4.300                 11.2000                 0.48000
30   3.500                  3.6000                 0.12000
32   4.100                  0.7200                 0.02900
34   0.055                 11.1000                 0.00610
45  20.800                  0.1400                 0.02900
47   9.100                  3.1000                 0.28000
52   9.300                  2.6000                 0.24000
57   2.600                  3.1000                 0.08200
58  10.300                  2.0000                 0.21000
61   7.400                  4.2000                 0.31000
64   0.560                 25.7000                 0.14000
66   5.000                  3.8000                 0.19000
67   5.800                  7.7000                 0.45000
69  15.300                  1.9000                 0.29000
80   7.800                  1.6000                 0.13000
82   5.100                  6.7000                 0.34000
85   8.100                  2.8000                 0.23000
89   0.039                  1.6000                 0.00063
93   4.200                  2.5000                 0.11000
97  16.600                  0.4600                 0.07600
98  14.300                  3.2000                 0.46000
101  4.500                  1.6000                 0.07100
103  6.800                  6.1000                 0.41000
104  0.170                 22.9000                 0.03900
110 15.400                  2.2000                 0.34000
111 10.900                  7.4000                 0.81000
115  0.320                 15.7000                 0.05000
117  6.000                  0.3500                 0.02100
118 10.100                  0.7500                 0.07600
119  0.000                  0.0660                 0.00000
124  6.400                  4.2000                 0.27000
127  2.000                  0.5300                 0.01100
136  3.400                 22.3000                 0.76000
142  7.400                  3.9000                 0.29000
148  1.400                 12.7000                 0.17000
149  6.500                  1.3000                 0.08400
151  3.900                 10.9000                 0.43000
152 14.700                  0.3600                 0.05300
156 13.100                  0.0065                 0.00085
157  1.700                  2.3000                 0.03800
158  4.900                  9.2000                 0.45000
162  4.700                  1.9000                 0.08700
168  1.700                  7.7000                 0.13000
169  5.000                 11.0000                 0.55000